### ISSUE TITLE
Duplicate test names cause errors

### ISSUE THREAD

**Issue by rcdailey** [philsquared/Catch#472]
So I started creating 1 test executable per class that I test. This became unwieldy after many classes came under test, as now I had hundreds of projects in my visual studio solution (CMake generated these for me).

I have now condensed my tests down to 1 project per module (multiple classes under test in 1 project, 1 translation unit per test for each class). This yields bigger tests that run more test cases and run for longer, however now I have some naming conflicts. It's common for me to have a test case like so:

```
TEST_CASE("Test Construction", "[class1]")
```

And in another translation unit, for a different class:

```
TEST_CASE("Test Construction", "[class2]")
```

However my test executable fails saying that two test cases with the same name were found. Why does it matter if the names are duplicated? The names, as far as I understood, were for documentation purposes. Do you not scope tests based on tags and/or translation unit? What is the proper structure here? How do I solve this problem?

**Comment by martinmoene** [comment]
This issue is likely related to issue #59.

Why not (also) use a proposition such as `class1 constructs properly` for the name of the test case?


I've created a gist before that I should probably adapt to show two source files and to use https://gist.github.com/martinmoene/c4240791bfd076c87e45

**Comment by Sarev0k** [comment]
Wouldn't it be preferable to optionally have the testing framework append some configurable prefix to test names?

I have my Catch tests segregated to a unique test file per class under test, and in some instances I have the same testCase name for two different classes.  Since I'm using different cpp files for each class, I would have expected that to be enough to prevent conflicts.

However, since this is not the case, I'm resorting to the following:
```c++
#define TEST_PREFIX "MyTestClass::"

TEST_CASE(TEST_PREFIX "testCaseName") {
    // ...
}
```

**Comment by rcdailey** [comment]
@Sarev0k I do the same thing for the tags (so that I can run all tests for a given class via a single tag).

At the moment it doesn't make sense to redundantly manage a prefix for the test case name either. I think Catch should utilize some scoping or name mangling mechanisms to generate unique names as it requires. This is an implementation detail that I shouldn't have to care about.

Maybe I'm missing some fundamental design concepts here, but that's just my observation so far.

I'm happy to contribute a code change if I can get some guidance from the author on what the problem is (if any) and a good way to fix it.

**Comment by martinmoene** [comment]
See also issue #209, pull request #210.

I expect another workaround is to put all test cases in one big outer (anonymous) namespace block in each .cpp file (can't try it at the moment though).

**Comment by martinmoene** [comment]
Notification: edited previous comment at 26-Jul-2015, 21:34 GMT

**Comment by Sarev0k** [comment]
Even if it's not done automatically based on cpp filename.

I think It would still be helpful if Catch provided a Macro I could override that would prefix all my test cases in a file with a specific string.

This would allow me to do the following:
```c++
#define TEST_NAME_PREFIX "MyTestFilePrefix"

TEST_CASE("testFoo") {
    // ...
}
```

Which would provide a test with the name of `MyTestFilePrefix::testFoo`.  With the added benefit that I don't have to manually prefix `TEST_CASE` names with `TEST_NAME_PREFIX` or redefine the TEST_CASE macro to do this for me.

I also believe that by expanding this concept to also include tagging these tests by default would also allow @rcdailey to run only tests of a specific file, without needing to manually tag them all.

**Comment by rcdailey** [comment]
@philsquared Has this been addressed yet? I'm having to do some obscure workarounds:

```
#define MAIN_TAG "[MyClass]"

//....

TEST_CASE(MAIN_TAG " This is my test case", MAIN_TAG)
{
    ......
}
```

**Comment by rcdailey** [comment]
Just wanted to ping this issue and see if there are any resolutions to this? Has this been addressed in a prior release?

**Comment by Sarev0k** [comment]
It looks like this may have been resolved in version 1.4.0 which incorporated philsquared/Catch/pull/351.

**Comment by philsquared** [comment]
I believe it was 1.5.0, incorporating #608 (thanks again, @rcdailey) - but, yes, I didn't report back here (or, in #608).

**Comment by rcdailey** [comment]
I did test this again with the __COUNTER__ change but I still see the problem (hence why #608 was still active). Happy to help diagnose why counter still wasn't working, I didn't dig too deep on it.

Let me create a sample project that reproduces the problem.

**Comment by rcdailey** [comment]
Here is a sample I created:
https://gist.github.com/rcdailey/9c757053bc49409a0458c90617d00122

I used Visual Studio 2015 as my CMake generator to create this project. Enable exception breakpoints for C++ and you will get a throw due to duplicate test case names. So either the `__COUNTER__` solution didn't work, or I'm confused about what it was supposed to really fix.

Let me know if you're able to reproduce the issue.

**Comment by philsquared** [comment]
I've been catching up on my unread emails, as well as GitHub issues, and have recently chatted with @rcdailey over email about this.
The issue is with the test name (the string) rather than the generated test function name - so the `__COUNTER__` won't help.
My first suggestion, which fits with @martinmoene's original comments in this thread, was to just make the names unique - but incorporating the name of the class under test (in the example) into the test name - which I think is more informative anyway.

I did also make another suggestion, which was to revert to the original approach for test naming in Catch: use the name field as a uniquely identifiable string, possibly hierarchical - and not necessarily descriptive (could be a guid if you like) - then use the second field as a free form description - which doesn't have to be unique. This still works because only content in square brackets is considered tags in the second field.

**Comment by horenmar** [comment]
Since there has been no follow-up in two months, I am going to close this issue.
