### ISSUE TITLE
Generated xml is broken

### ISSUE THREAD

**Issue by mrpi** [philsquared/Catch#625]
The xml writer uses the escape sequence "&#xXX;" incorrectly. Further details are described here #588.
I am just creating this bug report, so that the problem is not being overlooked.

**Comment by gatopeich** [comment]
Breaking my builds, too

**Comment by philsquared** [comment]
I believe this one is fixed now? (as of Build 1.5.7). Please confirm and/ or close.

**Comment by mrpi** [comment]
Still broken. Char to Int overflows and creates sequences like `&#xFFFFFFE5;`

**Comment by gatopeich** [comment]
I am working with a "works for me" patch...

**Comment by philsquared** [comment]
Could you give a more complete example of what is going wrong for you (assuming it still is in 1.6.0).
The example given in #588 seems to work for me at this point.

**Comment by philsquared** [comment]
Sorry ignore that - I was thinking of a different issue.
Looks like #588 may still have some outstanding parts.

**Comment by philsquared** [comment]
The encoding issues in the referenced ticket, #588, were fixed in February and that ticket was closed.
Is there any more to this ticket or can we close this one,  too?
Or, if not, could you give any more details?

**Comment by horenmar** [comment]
Since there hasn't been any follow-up in two months, I am gonna close this.
